num_judges: 3

debaters:
  - id: x-ai-grok-4.1-fast
    provider: openrouter
    model: x-ai/grok-4.1-fast
    token_limit: null
    parameters:
      temperature: 0.35

  - id: deepseek-deepseek-v3.2
    provider: openrouter
    model: deepseek/deepseek-v3.2
    token_limit: null
    parameters:
      temperature: 0.35

judges:
  - id: x-ai-grok-4.1-fast
    provider: openrouter
    model: x-ai/grok-4.1-fast
    token_limit: null
    prompt_style: default
    parameters:
      temperature: 0.0

  - id: deepseek-deepseek-v3.2
    provider: openrouter
    model: deepseek/deepseek-v3.2
    token_limit: null
    prompt_style: default
    parameters:
      temperature: 0.0

  - id: google-gemini-3-flash-preview
    role: debater
    provider: openrouter
    model: google/gemini-3-flash-preview
    token_limit: null
    prompt_style: default
    parameters:
      temperature: 0.0
