num_judges: 3

debaters:
  - id: moonshotai-kimi-k2-thinking
    provider: openrouter
    model: moonshotai/kimi-k2-thinking
    token_limit: null
    parameters:
      temperature: 0.35

  - id: claude-sonnet-4.5
    provider: openrouter
    model: anthropic/claude-sonnet-4.5
    token_limit: null
    parameters:
      temperature: 0.35

judges:
  - id: x-ai-grok-4.1-fast
    provider: openrouter
    model: x-ai/grok-4.1-fast
    token_limit: null
    prompt_style: default
    parameters:
      temperature: 0.0

  - id: deepseek-deepseek-v3.2
    provider: openrouter
    model: deepseek/deepseek-v3.2
    token_limit: null
    prompt_style: default
    parameters:
      temperature: 0.0

  - id: openai-gpt-5.1
    provider: openrouter
    model: openai/gpt-5.1
    token_limit: null
    prompt_style: default
    parameters:
      temperature: 0.0
